name: Deploy Electron App

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: macos-latest # Using macOS to build for all platforms

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build shared package
        run: pnpm --filter @mcp_router/shared build
      
      - name: Publish to GitHub Releases
        env:
          # The GITHUB_TOKEN is automatically provided by GitHub Actions
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: pnpm --filter @mcp_router/electron publish